apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mysql-deployment
spec:
  replicas: 2
  minReadySeconds: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      hostNetwork: true
      containers:
      - name: mysql
        image: csporg/mysql
        ports:
        - containerPort: 80
