apiVersion: v1
kind: Pod
metadata:
    name: mysql-pod
    labels: 
      env: dev
      server: app
spec:
     containers:
     - name: mysql 
       image: csporg/mysql
       ports:
       - containerPort: 3306
